/**
 * Municípios do Maranhão com população estimada (IBGE Censo 2022)
 * Ordenados alfabeticamente
 */
export interface MaranhaoCityData {
    name: string;
    population: number;
}

export const MARANHAO_CITIES: MaranhaoCityData[] = [
    { name: "Açailândia", population: 113822 },
    { name: "Afonso Cunha", population: 6281 },
    { name: "Água Doce do Maranhão", population: 12895 },
    { name: "Alcântara", population: 22139 },
    { name: "Aldeias Altas", population: 26765 },
    { name: "Altamira do Maranhão", population: 20299 },
    { name: "Alto Alegre do Maranhão", population: 31057 },
    { name: "Alto Alegre do Pindaré", population: 34085 },
    { name: "Alto Parnaíba", population: 10765 },
    { name: "Amapá do Maranhão", population: 7616 },
    { name: "Amarante do Maranhão", population: 42378 },
    { name: "Anajatuba", population: 27135 },
    { name: "Anapurus", population: 15948 },
    { name: "Apicum-Açu", population: 15830 },
    { name: "Araguanã", population: 14848 },
    { name: "Araioses", population: 47321 },
    { name: "Arame", population: 32767 },
    { name: "Arari", population: 29495 },
    { name: "Axixá", population: 11831 },
    { name: "Bacabal", population: 103359 },
    { name: "Bacabeira", population: 16604 },
    { name: "Bacuri", population: 17089 },
    { name: "Bacurituba", population: 6256 },
    { name: "Balsas", population: 97534 },
    { name: "Barão de Grajaú", population: 18098 },
    { name: "Barra do Corda", population: 88494 },
    { name: "Barreirinhas", population: 62844 },
    { name: "Bela Vista do Maranhão", population: 12516 },
    { name: "Belágua", population: 7613 },
    { name: "Benedito Leite", population: 5765 },
    { name: "Bequimão", population: 22281 },
    { name: "Bernardo do Mearim", population: 6494 },
    { name: "Boa Vista do Gurupi", population: 9074 },
    { name: "Bom Jardim", population: 42891 },
    { name: "Bom Jesus das Selvas", population: 32774 },
    { name: "Bom Lugar", population: 15795 },
    { name: "Brejo", population: 35972 },
    { name: "Brejo de Areia", population: 4048 },
    { name: "Buriti", population: 28723 },
    { name: "Buriti Bravo", population: 23652 },
    { name: "Buriticupu", population: 72358 },
    { name: "Buritirana", population: 15474 },
    { name: "Cachoeira Grande", population: 9018 },
    { name: "Cajapió", population: 11065 },
    { name: "Cajari", population: 19958 },
    { name: "Campestre do Maranhão", population: 14302 },
    { name: "Cândido Mendes", population: 19934 },
    { name: "Cantanhede", population: 22147 },
    { name: "Capinzal do Norte", population: 11991 },
    { name: "Carolina", population: 24020 },
    { name: "Carutapera", population: 23618 },
    { name: "Caxias", population: 164880 },
    { name: "Cedral", population: 10894 },
    { name: "Central do Maranhão", population: 8248 },
    { name: "Centro do Guilherme", population: 13166 },
    { name: "Centro Novo do Maranhão", population: 19482 },
    { name: "Chapadinha", population: 79091 },
    { name: "Cidelândia", population: 14189 },
    { name: "Codó", population: 122597 },
    { name: "Coelho Neto", population: 48315 },
    { name: "Colinas", population: 42186 },
    { name: "Conceição do Lago-Açu", population: 17636 },
    { name: "Coroatá", population: 67126 },
    { name: "Cururupu", population: 35104 },
    { name: "Davinópolis", population: 13034 },
    { name: "Dom Pedro", population: 23692 },
    { name: "Duque Bacelar", population: 11261 },
    { name: "Esperantinópolis", population: 19068 },
    { name: "Estreito", population: 42363 },
    { name: "Feira Nova do Maranhão", population: 8330 },
    { name: "Fernando Falcão", population: 10004 },
    { name: "Formosa da Serra Negra", population: 19396 },
    { name: "Fortaleza dos Nogueiras", population: 12750 },
    { name: "Fortuna", population: 16188 },
    { name: "Godofredo Viana", population: 10965 },
    { name: "Gonçalves Dias", population: 18018 },
    { name: "Governador Archer", population: 10795 },
    { name: "Governador Edison Lobão", population: 18290 },
    { name: "Governador Eugênio Barros", population: 17948 },
    { name: "Governador Luiz Rocha", population: 7564 },
    { name: "Governador Newton Bello", population: 12999 },
    { name: "Governador Nunes Freire", population: 25994 },
    { name: "Graça Aranha", population: 6583 },
    { name: "Grajaú", population: 68878 },
    { name: "Guimarães", population: 13612 },
    { name: "Humberto de Campos", population: 28480 },
    { name: "Icatu", population: 26885 },
    { name: "Igarapé do Meio", population: 13988 },
    { name: "Igarapé Grande", population: 11985 },
    { name: "Imperatriz", population: 259337 },
    { name: "Itaipava do Grajaú", population: 15838 },
    { name: "Itapecuru Mirim", population: 67221 },
    { name: "Itinga do Maranhão", population: 25785 },
    { name: "Jatobá", population: 9420 },
    { name: "Jenipapo dos Vieiras", population: 17044 },
    { name: "João Lisboa", population: 22877 },
    { name: "Joselândia", population: 18457 },
    { name: "Junco do Maranhão", population: 4382 },
    { name: "Lago da Pedra", population: 48567 },
    { name: "Lago do Junco", population: 11019 },
    { name: "Lago dos Rodrigues", population: 10096 },
    { name: "Lago Verde", population: 16063 },
    { name: "Lagoa do Mato", population: 11286 },
    { name: "Lagoa Grande do Maranhão", population: 11156 },
    { name: "Lajeado Novo", population: 7571 },
    { name: "Lima Campos", population: 11714 },
    { name: "Loreto", population: 12208 },
    { name: "Luís Domingues", population: 7192 },
    { name: "Magalhães de Almeida", population: 18491 },
    { name: "Maracaçumé", population: 21503 },
    { name: "Marajá do Sena", population: 9288 },
    { name: "Maranhãozinho", population: 14637 },
    { name: "Mata Roma", population: 15972 },
    { name: "Matinha", population: 24070 },
    { name: "Matões", population: 32547 },
    { name: "Matões do Norte", population: 16373 },
    { name: "Milagres do Maranhão", population: 9108 },
    { name: "Mirador", population: 21449 },
    { name: "Miranda do Norte", population: 25534 },
    { name: "Mirinzal", population: 14772 },
    { name: "Monção", population: 34457 },
    { name: "Montes Altos", population: 10203 },
    { name: "Morros", population: 19804 },
    { name: "Nina Rodrigues", population: 13835 },
    { name: "Nova Colinas", population: 5234 },
    { name: "Nova Iorque", population: 4828 },
    { name: "Nova Olinda do Maranhão", population: 19931 },
    { name: "Olho d'Água das Cunhãs", population: 19715 },
    { name: "Olinda Nova do Maranhão", population: 14306 },
    { name: "Paço do Lumiar", population: 122959 },
    { name: "Palmeirândia", population: 18780 },
    { name: "Paraibano", population: 11975 },
    { name: "Parnarama", population: 34772 },
    { name: "Passagem Franca", population: 17838 },
    { name: "Pastos Bons", population: 20069 },
    { name: "Paulino Neves", population: 16420 },
    { name: "Paulo Ramos", population: 21011 },
    { name: "Pedreiras", population: 40274 },
    { name: "Pedro do Rosário", population: 25137 },
    { name: "Penalva", population: 38024 },
    { name: "Peri Mirim", population: 14928 },
    { name: "Peritoró", population: 22405 },
    { name: "Pindaré-Mirim", population: 33050 },
    { name: "Pinheiro", population: 82374 },
    { name: "Pio XII", population: 22015 },
    { name: "Pirapemas", population: 17987 },
    { name: "Poção de Pedras", population: 19825 },
    { name: "Porto Franco", population: 24611 },
    { name: "Porto Rico do Maranhão", population: 6985 },
    { name: "Presidente Dutra", population: 48148 },
    { name: "Presidente Juscelino", population: 12021 },
    { name: "Presidente Médici", population: 6260 },
    { name: "Presidente Sarney", population: 19263 },
    { name: "Presidente Vargas", population: 11554 },
    { name: "Primeira Cruz", population: 14673 },
    { name: "Raposa", population: 30553 },
    { name: "Riachão", population: 22008 },
    { name: "Ribamar Fiquene", population: 8404 },
    { name: "Rosário", population: 42133 },
    { name: "Sambaíba", population: 5698 },
    { name: "Santa Filomena do Maranhão", population: 8133 },
    { name: "Santa Helena", population: 43998 },
    { name: "Santa Inês", population: 88870 },
    { name: "Santa Luzia", population: 77868 },
    { name: "Santa Luzia do Paruá", population: 25218 },
    { name: "Santa Quitéria do Maranhão", population: 24456 },
    { name: "Santa Rita", population: 36028 },
    { name: "Santana do Maranhão", population: 13082 },
    { name: "Santo Amaro do Maranhão", population: 15131 },
    { name: "Santo Antônio dos Lopes", population: 14469 },
    { name: "São Benedito do Rio Preto", population: 20046 },
    { name: "São Bento", population: 42153 },
    { name: "São Bernardo", population: 28381 },
    { name: "São Domingos do Azeitão", population: 7115 },
    { name: "São Domingos do Maranhão", population: 35632 },
    { name: "São Félix de Balsas", population: 4700 },
    { name: "São Francisco do Brejão", population: 12474 },
    { name: "São Francisco do Maranhão", population: 12284 },
    { name: "São João Batista", population: 20860 },
    { name: "São João do Carú", population: 14858 },
    { name: "São João do Paraíso", population: 11776 },
    { name: "São João do Soter", population: 18619 },
    { name: "São João dos Patos", population: 26673 },
    { name: "São José de Ribamar", population: 179028 },
    { name: "São José dos Basílios", population: 8066 },
    { name: "São Luís", population: 1108975 },
    { name: "São Luís Gonzaga do Maranhão", population: 20934 },
    { name: "São Mateus do Maranhão", population: 42135 },
    { name: "São Pedro da Água Branca", population: 13455 },
    { name: "São Pedro dos Crentes", population: 4870 },
    { name: "São Raimundo das Mangabeiras", population: 19131 },
    { name: "São Raimundo do Doca Bezerra", population: 5502 },
    { name: "São Roberto", population: 6518 },
    { name: "São Vicente Ferrer", population: 21385 },
    { name: "Satubinha", population: 12430 },
    { name: "Senador Alexandre Costa", population: 10776 },
    { name: "Senador La Rocque", population: 17861 },
    { name: "Serrano do Maranhão", population: 11025 },
    { name: "Sítio Novo", population: 18655 },
    { name: "Sucupira do Norte", population: 10375 },
    { name: "Sucupira do Riachão", population: 5546 },
    { name: "Tasso Fragoso", population: 8868 },
    { name: "Timbiras", population: 29168 },
    { name: "Timon", population: 174477 },
    { name: "Trizidela do Vale", population: 22659 },
    { name: "Tufilândia", population: 6392 },
    { name: "Tuntum", population: 41109 },
    { name: "Turiaçu", population: 36262 },
    { name: "Turilândia", population: 23799 },
    { name: "Tutóia", population: 57811 },
    { name: "Urbano Santos", population: 28036 },
    { name: "Vargem Grande", population: 53778 },
    { name: "Viana", population: 52792 },
    { name: "Vila Nova dos Martírios", population: 13642 },
    { name: "Vitória do Mearim", population: 33582 },
    { name: "Vitorino Freire", population: 32481 },
    { name: "Zé Doca", population: 52513 },
];

/** Helper: busca dados de uma cidade pelo nome */
export function findCityData(name: string): MaranhaoCityData | undefined {
    return MARANHAO_CITIES.find((c) => c.name === name);
}
